#!/usr/bin/env bash

# NAME
#   monitor - monitor wifi networks
#
# SYNOPSIS
#   monitor [NETWORK...]
#
# OUTPUT
#   TSV lines in the format:
#     iso <tab> timestamp <tab> ssid <tab> bssid <tab> channel <tab> rssi
#
# DEPENDENCIES
#   - scan = for the scanning

while true; do ./scan "$@" ; done
